module.exports = {
  ADD_MOVIE_TO_WATCH: "ADD_MOVIE_TO_WATCH",
  DELETE_MOVIE_TO_WATCH: "DELETE_MOVIE_TO_WATCH",
  ADD_WATCHED_MOVIE: "ADD_WATCHED_MOVIE",
  DELETE_WATCHED_MOVIE: "DELETE_WATCHED_MOVIE",
  CHANGE_WATCHED_MOVIE_RATING: "CHANGE_WATCHED_MOVIE_RATING",
  SET_ON_GOING_ACTION: "SET_ON_GOING_ACTION",
  RESET_ON_GOING_ACTION: "RESET_ON_GOING_ACTION",
};
